---

# Any ignore directives should be uncommented in downstream projects to disable
# Dependabot updates for the given dependency. Downstream projects will get
# these updates when the pull request(s) in the appropriate skeleton are merged
# and Lineage processes these changes.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Managed by cisagov/skeleton-generic
      - dependency-name: actions/cache
      - dependency-name: actions/checkout
      - dependency-name: actions/setup-go
      - dependency-name: actions/setup-python
      - dependency-name: hashicorp/setup-terraform
      - dependency-name: mxschmitt/action-tmate

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    # Managed by cisagov/skeleton-tf-module
    ignore:
      - dependency-name: "hashicorp/aws"

  - package-ecosystem: "terraform"
    directory: "/audit"
    schedule:
      interval: "weekly"
    # Managed by cisagov/skeleton-tf-module
    ignore:
      - dependency-name: "hashicorp/aws"

  - package-ecosystem: "terraform"
    directory: "/dns"
    schedule:
      interval: "weekly"
    # Managed by cisagov/skeleton-tf-module
    ignore:
      - dependency-name: "hashicorp/aws"

  - package-ecosystem: "terraform"
    directory: "/dynamic"
    schedule:
      interval: "weekly"
    # Managed by cisagov/skeleton-tf-module
    ignore:
      - dependency-name: "hashicorp/aws"

  - package-ecosystem: "terraform"
    directory: "/images"
    schedule:
      interval: "weekly"
    # Managed by cisagov/skeleton-tf-module
    ignore:
      - dependency-name: "hashicorp/aws"

  - package-ecosystem: "terraform"
    directory: "/log-archive"
    schedule:
      interval: "weekly"
    # Managed by cisagov/skeleton-tf-module
    ignore:
      - dependency-name: "hashicorp/aws"

  - package-ecosystem: "terraform"
    directory: "/master"
    schedule:
      interval: "weekly"
    # Managed by cisagov/skeleton-tf-module
    ignore:
      - dependency-name: "hashicorp/aws"

  - package-ecosystem: "terraform"
    directory: "/shared-services"
    schedule:
      interval: "weekly"
    # Managed by cisagov/skeleton-tf-module
    ignore:
      - dependency-name: "hashicorp/aws"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    # Managed by cisagov/skeleton-tf-module
    ignore:
      - dependency-name: "hashicorp/aws"

  - package-ecosystem: "terraform"
    directory: "/users"
    schedule:
      interval: "weekly"
    # Managed by cisagov/skeleton-tf-module
    ignore:
      - dependency-name: "hashicorp/aws"
