---

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/audit"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "terraform"
    directory: "/dns"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "terraform"
    directory: "/dynamic"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "terraform"
    directory: "/images"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "terraform"
    directory: "/log-archive"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "terraform"
    directory: "/master"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "terraform"
    directory: "/shared-services"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "terraform"
    directory: "/users"
    schedule:
      interval: "weekly"
